# Dockerfile
FROM golang:1.21-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o /gin-server ./cmd/server

FROM alpine:latest  
RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy the pre-built binary file from the previous stage.
COPY --from=builder /gin-server .

# Expose the port the app runs on.
EXPOSE 8080

# Run the binary.
CMD ["./gin-server"]